name: Service health check

on:
  push:
    branches:
      - main

steps:
  - name: Check the deployed service URL
    uses: jtalk/url-health-check-action@v4
    with:
      url: ${{ vars.DEPLOYMENT_URL }}